input_name: '1021.jpg'
class_num: 2
class_name: ['bent', 'tee']
generate_type: 'opencv'
resolution: [640, 480]
# detect_method: 'pipe_net'
detect_method: 'yolov8'

detect:
  rgb_path: './data/input/simu/rgb/' 
  depth_path: './data/input/simu/depth/' 
  pipe_net:
    config_path: './config/pipe_net.yaml' 
    weights_path: './data/detect/weights/pipe_net/yolov3_015000.pth'
    output_path: './data/detect/results/pipe_net/'
    output_name: 'detect.jpg'
  yolov8:
    weights_path: './data/detect/weights/yolov8/best.pt'
    conf_val: 0.2
    output_path: './data/detect/results/yolov8/'
    output_name: 'detect.jpg'

pose:
  name: gen6d_pretrain
  type: gen6d

  output_path: './data/pose/results/'

  detector: pose_estimate/configs/detector/detector_pretrain.yaml
  selector: pose_estimate/configs/selector/selector_pretrain.yaml
  refiner:  pose_estimate/configs/refiner/refiner_pretrain.yaml

  ref_resolution: 128   
  ref_view_num: 64      
  det_ref_view_num: 32 
  refine_iter: 3       

isometric:
  threshold_angle: 15
  output_cv_path: './data/isometric/results/images/2d_result.jpg'
  output_iso_path: './data/isometric/results/images/iso_result.jpg'
  output_dxf_path: './data/isometric/results/dxf/isometric.dxf'

  depth_path: './data/input/depth/'
  initial_position: 0

  dimtxt: 30
  dimdex: 0
  dimasz: 20
  dimblk: 'OPEN'
  dimclrd: 3
  dimclre: 3

  dimdistance: 25