img_path: './data/detect/datasets/pipe/test/images/3.png'
class_num: 2
class_name: ['bent', 't-junc']
generate_type: 'opencv'

detect:
  model_path: './data/detect/weights/best.pt'
  conf_val: 0.65
  output_path: './data/detect/result/'

pose:
  name: gen6d_pretrain
  type: gen6d

  output_path: './data/pose/result/'

  detector: pose_estimate/configs/detector/detector_pretrain.yaml
  selector: pose_estimate/configs/selector/selector_pretrain.yaml
  refiner:  pose_estimate/configs/refiner/refiner_pretrain.yaml

  ref_resolution: 128   
  ref_view_num: 64      
  det_ref_view_num: 32 
  refine_iter: 3       

isometric:
  resolution: [640, 480]
  threshold_angle: 35
  output_cv_path: './data/isometric/results/2d_result.jpg'
  output_iso_path: './data/isometric/results/iso_result.jpg'