input_name: '1000.png'
class_num: 2
class_name: ['bent', 't-junc']
generate_type: 'opencv'

detect:
  rgb_path: './data/input/rgb/' 
  model_path: './data/detect/weights/best.pt'
  conf_val: 0.65
  output_path: './data/detect/results/'
  output_name: 'detect.jpg'

pose:
  name: gen6d_pretrain
  type: gen6d

  output_path: './data/pose/results/'

  detector: pose_estimate/configs/detector/detector_pretrain.yaml
  selector: pose_estimate/configs/selector/selector_pretrain.yaml
  refiner:  pose_estimate/configs/refiner/refiner_pretrain.yaml

  ref_resolution: 128   
  ref_view_num: 64      
  det_ref_view_num: 32 
  refine_iter: 3       

isometric:
  resolution: [640, 480]
  threshold_angle: 35
  output_cv_path: './data/isometric/results/images/2d_result.jpg'
  output_iso_path: './data/isometric/results/images/iso_result.jpg'
  output_dxf_path: './data/isometric/results/dxf/isometric.dxf'

  depth_path: './data/input/depth/'